x-variables:
  - &MARIADB_DATABASE       mariadb
  - &MARIADB_USER           mariadb
  - &MARIADB_PASSWORD       mariadb
  - &MARIADB_ROOT_PASSWORD  mariadb
  - &WORDPRESS_USERNAME     user
  - &WORDPRESS_PASSWORD     user

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      mariadb:
        condition: service_healthy

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:wordpress

    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  # db:
  #   image: mariadb:10.4
  #   restart: unless-stopped
  #   volumes:
  #     - mariadb-data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: mariadb
  #     MYSQL_DATABASE: mariadb
  #     MYSQL_USER: mariadb
  #     MYSQL_PASSWORD: mariadb

  mariadb:
    image: docker.io/bitnami/mariadb:latest
    # networks:
    # - internal
    # volumes:
    #   - mariadb-data:/bitnami/mariadb
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: *MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: *MARIADB_DATABASE
      MARIADB_USER: *MARIADB_USER
      MARIADB_PASSWORD: *MARIADB_PASSWORD
    healthcheck:
      test: ["CMD", "mariadb", "-h", "mariadb", "-u", *MARIADB_USER, "-pmariadb", *MARIADB_DATABASE, "-e", "exit"]
      interval: 30s
      timeout: 10s
      retries: 5

  wordpress:
    image: docker.io/bitnami/wordpress-nginx:latest
  #   # networks:
  #   # - internal
  #   # ports:
  #   # - 80:8080
  #   # - 443:8443
  #   # volumes:
  #   # - ./persistence/wordpress:/bitnami/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      WORDPRESS_DATABASE_HOST: mariadb
  #     WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: *MARIADB_DATABASE
      WORDPRESS_DATABASE_USER: *MARIADB_USER
      WORDPRESS_DATABASE_PASSWORD: *MARIADB_PASSWORD
      WORDPRESS_USERNAME: *WORDPRESS_USERNAME
      WORDPRESS_PASSWORD: *WORDPRESS_PASSWORD

  ubuntu:
    image: docker.io/ubuntu:latest
    command:
    - sh
    - -c
    - |
      apt -qq update
      apt install mariadb-client telnet curl -y
      sleep inf

volumes:
  mariadb-data:
