x-variables:
  - &MARIADB_DATABASE       wp_bitnami
  - &MARIADB_USER           wp_bitnami
  - &MARIADB_ROOT_PASSWORD  mariadb
  - &WORDPRESS_USERNAME     user
  - &WORDPRESS_PASSWORD     user

services:

  mariadb:
    image: docker.io/bitnami/mariadb:latest
    networks:
    - internal
    volumes:
    - ./persistence/mariadb:/bitnami/mariadb
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: *MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: *MARIADB_DATABASE
      MARIADB_USER: *MARIADB_USER
    healthcheck:
      test: ["CMD", "mariadb", "-h", "mariadb", "-u", *MARIADB_USER, *MARIADB_DATABASE, "-e", "exit"]
      interval: 30s
      timeout: 10s
      retries: 5

  wordpress:
    image: docker.io/bitnami/wordpress-nginx:latest
    networks:
    - internal
    ports:
    - 80:8080
    - 443:8443
    volumes:
    - ./persistence/wordpress:/bitnami/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      WORDPRESS_DATABASE_HOST: mariadb
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: *MARIADB_DATABASE
      WORDPRESS_DATABASE_USER: *MARIADB_USER
      WORDPRESS_USERNAME: *WORDPRESS_USERNAME
      WORDPRESS_PASSWORD: *WORDPRESS_PASSWORD

  # ubuntu:
  #   image: docker.io/ubuntu:latest
  #   command:
  #   - sh
  #   - -c
  #   - |
  #     apt -qq update
  #     apt install mariadb-client telnet curl -y
  #     tail -f /dev/null
  #   networks:
  #     - internal

networks:
  internal:
